services:
  proxy_nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - ${SSL_PORT}:${SSL_PORT}
      - ${HTTP_PORT}:${HTTP_PORT}
    environment:
      - SSL_PORT=${SSL_PORT}
      - HTTP_PORT=${HTTP_PORT}
      - SSL_DIR=${SSL_DIR}
      - CERT_FILE=test.pem
      - KEY_FILE=test.key
    networks:
      - ${NET_NAME}
    volumes:
      - ${PROXY_FILE}:${DEFAULT_NGX_CONF_FILE}:ro
      - ${HOST_SSL_DIR}:${CERT_FILE}:${SSL_DIR}/{$CERT_FILE}:ro
      - ${HOST_SSL_DIR}:${KEY_FILE}:${SSL_DIR}/{$KEY_FILE}:ro

  test_db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASS}

# add mysql roman privs, add to net
